import { useMemo, useState } from 'react';
import { Link } from 'react-router';

import { IssueOverlayPanel } from '@/components/results/IssueOverlayPanel';
import { Button } from '@/components/ui/button';
import { useLiveQuery } from '@/lib/app/use-live-query';
import { useServices } from '@/lib/app/services';
import {
  PATTERN_VIEWS,
  PATTERN_VIEW_LABEL,
  filterByRange,
  type PatternRange,
  type PatternView,
} from '@/lib/patterns/collect';
import { summarizePatterns, THIN_SHOT_COUNT } from '@/lib/patterns/summarize';
import { patternsSizeFactor, renderPatternsSvg } from '@/lib/render/patterns';
import { loadPatterns } from '@/lib/services/patterns';
import { formatMm } from '@/lib/scoring/format';

const RANGES: ReadonlyArray<{ id: PatternRange; label: string }> = [
  { id: 'last', label: 'Latest session' },
  { id: 'week', label: 'This week' },
  { id: '30', label: '30 days' },
  { id: '90', label: '90 days' },
  { id: 'all', label: 'All time' },
];

function percent(share: number): string {
  return `${Math.round(share * 100)}%`;
}

/** Route `#/patterns` (patterns.md §6): every recorded shot on each kind of target. View-only. */
export function PatternsPage() {
  const { ctx } = useServices();
  const { value, loading } = useLiveQuery(() => loadPatterns(ctx), [ctx]);
  const [view, setView] = useState<PatternView>('sight-in');
  const [range, setRange] = useState<PatternRange>('all');
  const [zoomed, setZoomed] = useState(false);
  const [issues, setIssues] = useState<string[]>([]);

  const kind = view.startsWith('precision') ? 'precision' : 'sighting';
  const shown = useMemo(
    () => (value === undefined ? [] : filterByRange(value.data.points[view], range, value.today)),
    [value, view, range],
  );
  const summary = useMemo(() => summarizePatterns(shown, kind), [shown, kind]);
  // One size for all four views, worked out from every shot ever recorded (patterns.md §5).
  const factor = useMemo(
    () =>
      value === undefined
        ? 1
        : patternsSizeFactor(PATTERN_VIEWS.map((v) => ({ kind: v.startsWith('precision') ? ('precision' as const) : ('sighting' as const), points: value.data.points[v] }))),
    [value],
  );
  const svg = useMemo(() => renderPatternsSvg({ kind, points: shown, summary, factor, issues }), [kind, shown, summary, factor, issues]);

  return (
    <main className="mx-auto flex min-h-dvh max-w-md flex-col gap-4 p-4 lg:max-w-6xl">
      <header className="flex items-center justify-between">
        <h1 className="text-xl font-semibold">Patterns</h1>
        <Link to="/" className="inline-flex min-h-11 items-center text-sm text-primary underline underline-offset-4">
          Home
        </Link>
      </header>

      <div role="group" aria-label="Target type" className="grid grid-cols-2 gap-2 sm:grid-cols-4">
        {PATTERN_VIEWS.map((id) => (
          <Button
            key={id}
            variant={id === view ? 'default' : 'outline'}
            className="h-11"
            aria-pressed={id === view}
            data-testid={`pattern-view-${id}`}
            onClick={() => setView(id)}
          >
            {PATTERN_VIEW_LABEL[id]}
          </Button>
        ))}
      </div>
      <div role="group" aria-label="Date range" className="grid grid-cols-2 gap-2 sm:grid-cols-5">
        {RANGES.map((r) => (
          <Button
            key={r.id}
            variant={r.id === range ? 'default' : 'outline'}
            className="h-11"
            aria-pressed={r.id === range}
            data-testid={`pattern-range-${r.id}`}
            onClick={() => setRange(r.id)}
          >
            {r.label}
          </Button>
        ))}
      </div>

      {loading && value === undefined ? (
        <p className="text-sm text-muted-foreground">Loading…</p>
      ) : (
        <div className="flex flex-col gap-4 lg:flex-row">
          <div className="min-w-0 flex-1">
            <div className="flex flex-col gap-2 lg:flex-row lg:items-start">
            <IssueOverlayPanel selected={issues} onChange={setIssues} className="lg:order-2 lg:w-48 lg:shrink-0" />
            <div className={`min-w-0 flex-1 lg:order-1 ${zoomed ? 'max-h-[80vh] overflow-auto' : ''}`}>
              <div
                data-testid="patterns-drawing"
                data-shots={shown.length}
                className={`${zoomed ? 'w-[200%]' : 'w-full'} [&>svg]:block [&>svg]:h-auto [&>svg]:w-full`}
                role="img"
                aria-label={`${PATTERN_VIEW_LABEL[view]}: ${shown.length} shots`}
                // Generated by our own pure renderer from numbers and constants only.
                dangerouslySetInnerHTML={{ __html: svg }}
              />
            </div>
            </div>
            <Button variant="outline" className="mt-2 h-11" data-testid="patterns-zoom" onClick={() => setZoomed(!zoomed)}>
              {zoomed ? 'Fit to width' : 'Zoom in'}
            </Button>
          </div>

          <section className="flex flex-col gap-1 text-sm lg:w-72" aria-label="Summary" data-testid="patterns-summary">
            <p className="font-medium" data-testid="patterns-counts">
              {summary.shots} {summary.shots === 1 ? 'shot' : 'shots'} · {summary.targets}{' '}
              {summary.targets === 1 ? 'target' : 'targets'} · {summary.sessions}{' '}
              {summary.sessions === 1 ? 'session' : 'sessions'}
            </p>
            {summary.shots === 0 ? (
              <p className="text-muted-foreground">No shots here yet.</p>
            ) : (
              <>
                {summary.thin && (
                  <p className="text-muted-foreground" data-testid="patterns-thin">
                    Patterns need more shots (at least {THIN_SHOT_COUNT}).
                  </p>
                )}
                {summary.mpiOffset !== null && (
                  <p>
                    Mean point of impact: {formatMm(Math.abs(summary.mpiOffset.xMm))} mm {summary.mpiOffset.xMm >= 0 ? 'right' : 'left'},{' '}
                    {formatMm(Math.abs(summary.mpiOffset.yMm))} mm {summary.mpiOffset.yMm >= 0 ? 'high' : 'low'}
                  </p>
                )}
                {summary.extremeSpreadMm !== null && <p>Widest spread: {formatMm(summary.extremeSpreadMm)} mm</p>}
                {summary.averageRing !== null && <p>Average ring: {summary.averageRing.toFixed(2)}</p>}
                {summary.ringCounts !== null && (
                  <p className="text-xs text-muted-foreground" data-testid="patterns-rings">
                    {summary.ringCounts
                      .map((n, ring) => ({ n, ring }))
                      .reverse()
                      .filter(({ n }) => n > 0)
                      .map(({ n, ring }) => `${ring}: ${percent(n / summary.shots)}`)
                      .join(' · ')}
                  </p>
                )}
                {summary.zoneHitShare !== null && <p>In the hit zone: {percent(summary.zoneHitShare)}</p>}
              </>
            )}
            {value !== undefined && value.data.leftOut > 0 && (
              <p className="text-xs text-muted-foreground" data-testid="patterns-left-out">
                {value.data.leftOut} {value.data.leftOut === 1 ? 'target' : 'targets'} left out (not analysed, or alignment not
                confirmed).
              </p>
            )}
          </section>
        </div>
      )}
    </main>
  );
}
