import { renderScoreStar } from '@/lib/render/diagram-marks';

/**
 * leaderboard.md §7: a board average in the same star as a precision target's score on the results screen and in the summary image
 * (REV-80/107): gold above 90, silver from 80, bronze from 70, and a plain circle below 70, the whole-number score written inside.
 */
export function ScoreMedal({ percent, testId }: { percent: number; testId?: string }) {
  const score = Math.round(percent);
  return (
    <span className="shrink-0" role="img" aria-label={`Average ${score}%`} data-testid={testId} data-score={score}>
      <svg
        viewBox="2 2 96 96"
        className="block size-14"
        aria-hidden="true"
        // Generated by our own pure renderer from a number only.
        dangerouslySetInnerHTML={{ __html: renderScoreStar(50, 50, score, 100) }}
      />
    </span>
  );
}
