import { describe, expect, it } from 'vitest';

import { metalBoutRows } from '@/lib/domain/coach-context-view';
import type { MetalContext } from '@/lib/domain/coach-context';
import { layoutBand, type BandModel } from '@/lib/render/composite-band';
import { renderMetalDiscs } from '@/lib/render/coach-metal';

const model = (over: Partial<BandModel> = {}): BandModel => ({
  scoring: 'Scoring: Official gauge touch',
  rows: [],
  showMpi: false,
  showRules: false,
  extra: [],
  goals: [],
  notes: null,
  athlete: null,
  footer: 'Generated by NordicAim created by KomplexMojo release abc1234',
  ...over,
});

const bout = (position: 'prone' | 'standing', discHits: boolean[], comboGroup: string | null): MetalContext => ({
  sessionDate: '2026-09-28',
  position,
  discHits,
  comboGroup,
  hitRate: discHits.filter(Boolean).length / 5,
  targetZone: null,
  race: null,
});

describe('analysis band: 545 Coach metal bouts (M29, REV-159, coach-context-import.md §6)', () => {
  it('no metal, or an empty list, draws the band exactly as before', () => {
    const before = layoutBand(model(), 1560);
    expect(layoutBand(model({ metal: [] }), 1560)).toEqual(before);
    expect(before.svg).not.toContain('metal-bout');
  });

  it('one row of five discs per bout, grouped by combo group then position', () => {
    const metal = metalBoutRows([
      bout('standing', [true, false, false, true, true], 'g-1'),
      bout('prone', [true, true, false, true, true], 'g-1'),
      bout('standing', [false, false, false, false, false], 'g-2'),
      bout('standing', [true, true, true, true, true], 'g-2'),
      bout('standing', [true, true, true, false, true], 'g-2'),
    ]);
    const { svg } = layoutBand(model({ metal }), 1560);
    const rows = [...svg.matchAll(/<g class="metal-bout" data-position="(\w+)" data-hits="(\d)">(.*?)<\/g>/g)];
    expect(rows.map((r) => [r[1], r[2]])).toEqual([
      ['prone', '4'],
      ['standing', '3'],
      ['standing', '0'],
      ['standing', '5'],
      ['standing', '4'],
    ]);
    for (const r of rows) expect((r[3]!.match(/<circle /g) ?? []).length).toBe(5);
    expect(rows[0]![3]).toContain('>Combo 1<');
    expect(rows[1]![3]).not.toContain('Combo');
    expect(rows[2]![3]).toContain('>Combo 2<');
    expect(svg).toContain('>Metal targets (545 Coach)<');
  });

  it('adds a 46 px gap and 34 px per bout to the band', () => {
    const base = layoutBand(model(), 1560).height;
    const three = metalBoutRows([bout('prone', [true, true, true, true, true], null), bout('prone', [true, true, true, true, true], null), bout('standing', [false, true, true, true, true], null)]);
    expect(layoutBand(model({ metal: three }), 1560).height).toBe(base + 46 + 3 * 34);
  });

  it('a hit is a filled disc and a miss an open ring, alpha to echo left to right', () => {
    const svg = renderMetalDiscs([true, false, true, false, false], 100, 50);
    const discs = [...svg.matchAll(/<circle cx="(\d+)" cy="50" r="11" fill="([^"]+)"[^>]*data-hit="(\w+)"/g)];
    expect(discs.map((d) => [Number(d[1]), d[3]])).toEqual([
      [100, 'true'],
      [130, 'false'],
      [160, 'true'],
      [190, 'false'],
      [220, 'false'],
    ]);
    expect(discs[0]![2]).not.toBe(discs[1]![2]);
  });
});
