import { describe, expect, it } from 'vitest';

import { coachTrends } from '@/lib/analysis/coach';
import { PATTERN_VIEWS, type PatternPoint, type PatternView } from '@/lib/patterns/collect';
import { summarizePatterns } from '@/lib/patterns/summarize';
import { dateLabelIndices, MAX_MARKED_SESSIONS, SERIES_COLOUR, shortDate } from '@/lib/render/trends-band';
import { renderTrendsSheet, type TrendsSheetInput } from '@/lib/render/trends-sheet';

// analysis.md §5 (REV-124): the coach image.

function sessions(n: number): Record<PatternView, PatternPoint[]> {
  const out: Record<PatternView, PatternPoint[]> = { 'sight-in': [], confirm: [], 'precision-prone': [], 'precision-standing': [] };
  for (let s = 0; s < n; s += 1) {
    const date = new Date(Date.UTC(2026, 0, 1 + s)).toISOString().slice(0, 10);
    for (const view of PATTERN_VIEWS) {
      for (let k = 0; k < 3; k += 1) {
        out[view].push({ xMm: k, yMm: -k, ring: 9, isX: false, zone: 'hit', photoId: `${s}-${view}`, sessionId: `s${s}`, sessionDate: date, sessionStamp: `${date}T10:00:00.000Z` });
      }
    }
  }
  return out;
}

function input(n: number, over: Partial<TrendsSheetInput> = {}): TrendsSheetInput {
  const byView = sessions(n);
  const views = Object.fromEntries(
    PATTERN_VIEWS.map((v) => [v, { points: byView[v], summary: summarizePatterns(byView[v], v.startsWith('precision') ? 'precision' : 'sighting') }]),
  ) as TrendsSheetInput['views'];
  return { rangeLabel: 'All time', views, factor: 1, trends: coachTrends(byView), release: 'abc1234', generatedAtLocal: '2026-09-27 18:00', ...over };
}

describe('renderTrendsSheet', () => {
  it('is 1440 wide and a fixed height: header, the 2 × 2 grid, five charts, footer', () => {
    const out = renderTrendsSheet(input(5));
    expect(out.width).toBe(1440);
    expect(out.height).toBe(120 + 1440 + (170 + 5 * 300 + 10) + 110);
    expect(out.svg).toContain(`height="${out.height}"`);
  });

  it('draws the four views, a legend and five charts, with no NaN anywhere', () => {
    const { svg } = renderTrendsSheet(input(5));
    for (const view of PATTERN_VIEWS) expect(svg).toContain(`data-view="${view}"`);
    for (const id of ['score', 'group', 'rms', 'mpiX', 'mpiY']) expect(svg).toContain(`data-metric="${id}"`);
    for (const colour of Object.values(SERIES_COLOUR)) expect(svg).toContain(colour);
    expect(svg).not.toContain('NaN');
  });

  it('prints the athlete line and the credit with the release', () => {
    const { svg } = renderTrendsSheet(input(3, { provenance: { name: 'A. Athlete', club: 'Club', stamp: '9F2C41AB-3D7E90B1C2A4' } }));
    expect(svg).toContain('Athlete: A. Athlete · Club · Stamp: 9F2C41AB-3D7E90B1C2A4');
    expect(svg).toContain('Generated by NordicAim created by KomplexMojo release abc1234');
    expect(renderTrendsSheet(input(3)).svg).not.toContain('Athlete:');
  });

  it('marks points while sessions are few, and draws the line alone past the limit', () => {
    const few = renderTrendsSheet(input(MAX_MARKED_SESSIONS)).svg.match(/<circle[^>]*r="6"[^>]*stroke="#EAF2F8"/g) ?? [];
    const many = renderTrendsSheet(input(MAX_MARKED_SESSIONS + 1)).svg.match(/<circle[^>]*r="6"[^>]*stroke="#EAF2F8"/g) ?? [];
    expect(few.length).toBe(5 * 4 * MAX_MARKED_SESSIONS); // five charts × four views
    expect(many.length).toBe(0);
  });

  it('still renders with no sessions in the range', () => {
    const out = renderTrendsSheet(input(0));
    expect(out.svg).toContain('No sessions in this range');
    expect(out.svg).toContain('No shots in this range');
    expect(out.svg).not.toContain('NaN');
  });
});

describe('session axis labels', () => {
  it('labels every session up to 8, else 8 spread evenly including the first and last', () => {
    expect(dateLabelIndices(3)).toEqual([0, 1, 2]);
    const many = dateLabelIndices(100);
    expect(many).toHaveLength(8);
    expect(many[0]).toBe(0);
    expect(many.at(-1)).toBe(99);
  });

  it('writes dates without the locale', () => {
    expect(shortDate('2026-09-21')).toBe('Sep 21');
    expect(shortDate('2026-01-05')).toBe('Jan 5');
  });
});
