import { describe, expect, it } from 'vitest';

import { coachAverages, coachTrends, mpiScale } from '@/lib/analysis/coach';
import { PATTERN_VIEWS, type PatternPoint, type PatternView } from '@/lib/patterns/collect';
import { summarizePatterns } from '@/lib/patterns/summarize';
import { shortDate } from '@/lib/render/trends-averages';
import { renderTrendsSheet, type TrendsSheetInput } from '@/lib/render/trends-sheet';

// analysis.md §5 (REV-124, REV-131): the coach image: the four Patterns drawings, then each view's averages in small boxes.

function sessions(n: number): Record<PatternView, PatternPoint[]> {
  const out: Record<PatternView, PatternPoint[]> = { 'sight-in': [], confirm: [], 'precision-prone': [], 'precision-standing': [] };
  for (let s = 0; s < n; s += 1) {
    const date = new Date(Date.UTC(2026, 0, 1 + s)).toISOString().slice(0, 10);
    for (const view of PATTERN_VIEWS) {
      for (let k = 0; k < 3; k += 1) {
        out[view].push({ xMm: k, yMm: -k, ring: 9, isX: false, zone: 'hit', photoId: `${s}-${view}`, sessionId: `s${s}`, sessionDate: date, sessionStamp: `${date}T10:00:00.000Z` });
      }
    }
  }
  return out;
}

function input(n: number, over: Partial<TrendsSheetInput> = {}): TrendsSheetInput {
  const byView = sessions(n);
  const views = Object.fromEntries(
    PATTERN_VIEWS.map((v) => [v, { points: byView[v], summary: summarizePatterns(byView[v], v.startsWith('precision') ? 'precision' : 'sighting') }]),
  ) as TrendsSheetInput['views'];
  return { rangeLabel: 'All time', views, factor: 1, trends: coachTrends(byView), release: 'abc1234', generatedAtLocal: '2026-09-27 18:00', ...over };
}

describe('renderTrendsSheet', () => {
  it('is 1440 wide and a fixed height: header, the 2 × 2 grid, the averages band (four rows), footer', () => {
    const out = renderTrendsSheet(input(5));
    expect(out.width).toBe(1440);
    expect(out.height).toBe(120 + 1440 + (120 + 4 * 270 + 10) + 110);
    expect(out.svg).toContain(`height="${out.height}"`);
  });

  it('draws the four views, and per view four boxes and no trend chart, with no NaN anywhere', () => {
    const { svg } = renderTrendsSheet(input(5));
    for (const view of PATTERN_VIEWS) {
      expect(svg).toContain(`class="averages-row" data-view="${view}"`);
      for (const id of ['score', 'group', 'rms', 'mpi']) expect(svg).toContain(`data-view="${view}" data-metric="${id}"`);
    }
    expect(svg).not.toContain('trend-chart');
    expect(svg).not.toContain('trend-line');
    expect(svg).toContain('Averages in this range');
    expect(svg).not.toContain('NaN');
  });

  it('prints each view\'s averages: hit rate for sighting, score for precision, group, accuracy and the MPI in words', () => {
    // Every session has the same three shots (ring 9, in the hit zone) at (0,0), (1,−1), (2,−2).
    const { svg } = renderTrendsSheet(input(3));
    expect(svg.match(/>100%</g)).toHaveLength(2); // sight in and confirm
    expect(svg.match(/>90%</g)).toHaveLength(2); // prone and standing
    expect(svg.match(/>Hit rate</g)).toHaveLength(2);
    expect(svg.match(/>Score</g)).toHaveLength(2);
    expect(svg.match(/>1\.0 mm right · 1\.0 mm low</g)).toHaveLength(4);
    expect(svg.match(/>3 sessions</g)).toHaveLength(4);
  });

  it('prints the athlete line and the credit with the release', () => {
    const { svg } = renderTrendsSheet(input(3, { provenance: { name: 'A. Athlete', club: 'Club', stamp: '9F2C41AB-3D7E90B1C2A4' } }));
    expect(svg).toContain('Athlete: A. Athlete · Club · Stamp: 9F2C41AB-3D7E90B1C2A4');
    expect(svg).toContain('Generated by NordicAim created by KomplexMojo release abc1234');
    expect(renderTrendsSheet(input(3)).svg).not.toContain('Athlete:');
  });

  it('still renders with no sessions in the range', () => {
    const out = renderTrendsSheet(input(0));
    expect(out.svg).toContain('No sessions in this range');
    expect(out.svg).toContain('No shots in this range');
    expect(out.svg).not.toContain('mpi-mark');
    expect(out.svg).not.toContain('NaN');
  });
});

describe('the MPI boxes (REV-131)', () => {
  it('share one scale: the first of 5, 10, 20, 50 … mm at least 15% past the largest offset', () => {
    expect(mpiScale(0)).toBe(5);
    expect(mpiScale(4.3)).toBe(5);
    expect(mpiScale(4.4)).toBe(10);
    expect(mpiScale(12)).toBe(20);
    expect(mpiScale(600)).toBe(500);
    expect(coachAverages(input(3).trends).mpiScaleMm).toBe(5);
  });

  it('place the view\'s mark at its average MPI, +x right and +y up on the drawing', () => {
    // An offset of (+10, −2) mm on a ±20 mm box: the mark's centre is 10/20 of the half-size right and 2/20 below the centre.
    const byView = sessions(1);
    for (const view of PATTERN_VIEWS) byView[view] = byView[view].map((p) => ({ ...p, xMm: 10, yMm: -2 }));
    const trends = coachTrends(byView);
    expect(coachAverages(trends).mpiScaleMm).toBe(20);
    const { svg } = renderTrendsSheet({ ...input(1), trends });
    const start = svg.indexOf('data-view="confirm" data-metric="mpi"');
    const box = svg.slice(start, svg.indexOf('class="averages-row"', start));
    const [, tx, ty] = box.match(/class="mpi-mark" transform="translate\(([-\d.]+) ([-\d.]+)\) scale\(([\d.]+)\)"/)!;
    const cx = Number(box.match(/<circle cx="([\d.]+)" cy="([\d.]+)" r="75"/)![1]);
    const cy = Number(box.match(/<circle cx="([\d.]+)" cy="([\d.]+)" r="75"/)![2]);
    const s = 30 / 48;
    expect(Number(tx) + 48 * s).toBeCloseTo(cx + 37.5, 1);
    expect(Number(ty) + 46 * s).toBeCloseTo(cy + 7.5, 1);
    expect(box).toContain('10.0 mm right · 2.0 mm low');
    expect(box).toContain('data-role="confirm"');
  });

  it('averages each view over its sessions, each session counted once', () => {
    const byView = sessions(2);
    byView['precision-prone'] = byView['precision-prone'].map((p) => (p.sessionId === 's1' ? { ...p, ring: 7 } : p));
    const prone = coachAverages(coachTrends(byView)).views.find((v) => v.view === 'precision-prone')!;
    expect(prone.sessions).toBe(2);
    expect(prone.values.score).toBeCloseTo(80, 9); // (90 + 70) / 2
  });
});

describe('dates', () => {
  it('writes dates without the locale', () => {
    expect(shortDate('2026-09-21')).toBe('Sep 21');
    expect(shortDate('2026-01-05')).toBe('Jan 5');
  });
});
