import { describe, expect, it } from 'vitest';

import { coachAverages, coachTrends, mpiScale, trendOf } from '@/lib/analysis/coach';
import { PATTERN_VIEWS, type PatternPoint, type PatternView } from '@/lib/patterns/collect';
import { summarizePatterns } from '@/lib/patterns/summarize';
import { placeMpi, shortDate, TREND_COLOUR } from '@/lib/render/trends-averages';
import { renderTrendsSheet, type TrendsSheetInput } from '@/lib/render/trends-sheet';

// analysis.md §5 (REV-124, REV-131): the coach image: the four Patterns drawings, then each view's averages in small boxes.

function sessions(n: number): Record<PatternView, PatternPoint[]> {
  const out: Record<PatternView, PatternPoint[]> = { 'sight-in': [], confirm: [], 'precision-prone': [], 'precision-standing': [] };
  for (let s = 0; s < n; s += 1) {
    const date = new Date(Date.UTC(2026, 0, 1 + s)).toISOString().slice(0, 10);
    for (const view of PATTERN_VIEWS) {
      for (let k = 0; k < 3; k += 1) {
        out[view].push({ xMm: k, yMm: -k, ring: 9, isX: false, zone: 'hit', photoId: `${s}-${view}`, sessionId: `s${s}`, sessionDate: date, sessionStamp: `${date}T10:00:00.000Z` });
      }
    }
  }
  return out;
}

function input(n: number, over: Partial<TrendsSheetInput> = {}): TrendsSheetInput {
  const byView = sessions(n);
  const views = Object.fromEntries(
    PATTERN_VIEWS.map((v) => [v, { points: byView[v], summary: summarizePatterns(byView[v], v.startsWith('precision') ? 'precision' : 'sighting') }]),
  ) as TrendsSheetInput['views'];
  return { rangeLabel: 'All time', views, factor: 1, trends: coachTrends(byView), release: 'abc1234', generatedAtLocal: '2026-09-27 18:00', ...over };
}

describe('renderTrendsSheet', () => {
  it('is 1440 wide and a fixed height: header, the 2 × 2 grid, the averages band (four rows), footer', () => {
    const out = renderTrendsSheet(input(5));
    expect(out.width).toBe(1440);
    expect(out.height).toBe(120 + 1440 + (150 + 4 * 295 + 10) + 110);
    expect(out.svg).toContain(`height="${out.height}"`);
  });

  it('draws the four views, and per view four boxes and no trend chart, with no NaN anywhere', () => {
    const { svg } = renderTrendsSheet(input(5));
    for (const view of PATTERN_VIEWS) {
      expect(svg).toContain(`class="averages-row" data-view="${view}"`);
      for (const id of ['score', 'group', 'rms', 'mpi']) expect(svg).toContain(`data-view="${view}" data-metric="${id}"`);
    }
    expect(svg).not.toContain('trend-chart');
    expect(svg).not.toContain('trend-line');
    expect(svg).toContain('Averages in this range');
    expect(svg).not.toContain('NaN');
  });

  it('prints each view\'s averages: hit rate for sighting, score for precision, group, accuracy and the MPI in words', () => {
    // Every session has the same three shots (ring 9, in the hit zone) at (0,0), (1,−1), (2,−2).
    const { svg } = renderTrendsSheet(input(3));
    expect(svg.match(/>100%</g)).toHaveLength(2); // sight in and confirm
    expect(svg.match(/>90%</g)).toHaveLength(2); // prone and standing
    expect(svg.match(/>Hit rate</g)).toHaveLength(2);
    expect(svg.match(/>Score</g)).toHaveLength(2);
    expect(svg.match(/>avg 1\.0 mm right · 1\.0 mm low</g)).toHaveLength(4);
    expect(svg.match(/>3 sessions</g)).toHaveLength(4);
  });

  it('prints the athlete line and the credit with the release', () => {
    const { svg } = renderTrendsSheet(input(3, { provenance: { name: 'A. Athlete', club: 'Club', stamp: '9F2C41AB-3D7E90B1C2A4' } }));
    expect(svg).toContain('Athlete: A. Athlete · Club · Stamp: 9F2C41AB-3D7E90B1C2A4');
    expect(svg).toContain('Generated by NordicAim created by KomplexMojo release abc1234');
    expect(renderTrendsSheet(input(3)).svg).not.toContain('Athlete:');
  });

  it('still renders with no sessions in the range', () => {
    const out = renderTrendsSheet(input(0));
    expect(out.svg).toContain('No sessions in this range');
    expect(out.svg).toContain('No shots in this range');
    expect(out.svg).not.toContain('mpi-mark');
    expect(out.svg).not.toContain('NaN');
  });
});

describe('the MPI boxes (REV-131)', () => {
  it('share one scale: the first of 5, 10, 15, 20, 25 mm at least 15% past the largest offset, never wider than 25', () => {
    expect(mpiScale(0)).toBe(5);
    expect(mpiScale(4.3)).toBe(5);
    expect(mpiScale(4.4)).toBe(10);
    expect(mpiScale(12)).toBe(15);
    expect(mpiScale(17)).toBe(20);
    expect(mpiScale(18)).toBe(25);
    // REV-134: never wider than ±25 mm.
    expect(mpiScale(22)).toBe(25);
    expect(mpiScale(600)).toBe(25);
    expect(coachAverages(input(3).trends).mpiScaleMm).toBe(5);
  });

  it('place the view\'s mark at its average MPI, +x right and +y up on the drawing', () => {
    // An offset of (+10, −2) mm on a ±15 mm box.
    const byView = sessions(1);
    for (const view of PATTERN_VIEWS) byView[view] = byView[view].map((p) => ({ ...p, xMm: 10, yMm: -2 }));
    const trends = coachTrends(byView);
    expect(coachAverages(trends).mpiScaleMm).toBe(15);
    const { svg } = renderTrendsSheet({ ...input(1), trends });
    const start = svg.indexOf('data-view="confirm" data-metric="mpi"');
    const box = svg.slice(start, svg.indexOf('class="averages-row"', start));
    const [, tx, ty] = box.match(/class="mpi-mark" transform="translate\(([-\d.]+) ([-\d.]+)\) scale\(([\d.]+)\)"/)!;
    const cx = Number(box.match(/<circle cx="([\d.]+)" cy="([\d.]+)" r="75"/)![1]);
    const cy = Number(box.match(/<circle cx="([\d.]+)" cy="([\d.]+)" r="75"/)![2]);
    const s = 30 / 48;
    // On ±15 mm: 10/15 of the 75 px half-size right, 2/15 of it down.
    expect(Number(tx) + 48 * s).toBeCloseTo(cx + 50, 1);
    expect(Number(ty) + 46 * s).toBeCloseTo(cy + 10, 1);
    expect(box).not.toContain('mpi-off-scale');
    expect(box).toContain('10.0 mm right · 2.0 mm low');
    expect(box).toContain('data-role="confirm"');
  });

  it('averages each view over its sessions, each session counted once', () => {
    const byView = sessions(2);
    byView['precision-prone'] = byView['precision-prone'].map((p) => (p.sessionId === 's1' ? { ...p, ring: 7 } : p));
    const prone = coachAverages(coachTrends(byView)).views.find((v) => v.view === 'precision-prone')!;
    expect(prone.sessions).toBe(2);
    expect(prone.values.score).toBeCloseTo(80, 9); // (90 + 70) / 2
  });
});

describe('the MPI box shows each session, not only the average (REV-133)', () => {
  it('sessions on alternate sides average to centred, and the box says how far off they typically sat', () => {
    // Prone: 5 mm left, 5 mm right, 5 mm left then right again by the same: the average left/right is 0.
    const byView = sessions(4);
    const side = [-5, 5, -5, 5];
    byView['precision-prone'] = byView['precision-prone'].map((p) => ({ ...p, xMm: side[Number(p.sessionId.slice(1))]!, yMm: 0 }));
    const trends = coachTrends(byView);
    const prone = coachAverages(trends).views.find((v) => v.view === 'precision-prone')!;
    expect(prone.values.mpiX).toBeCloseTo(0, 12);
    expect(prone.mpiSessions).toEqual([
      { xMm: -5, yMm: 0 },
      { xMm: 5, yMm: 0 },
      { xMm: -5, yMm: 0 },
      { xMm: 5, yMm: 0 },
    ]);
    expect(prone.mpiTypicalMm).toBeCloseTo(5, 12);

    const { svg } = renderTrendsSheet({ ...input(4), trends });
    const start = svg.indexOf('data-view="precision-prone" data-metric="mpi"');
    const box = svg.slice(start, svg.indexOf('class="averages-row"', start));
    expect(box.match(/class="mpi-session"/g)).toHaveLength(4);
    expect(box).toContain('>avg centred · centred<');
    expect(box).toContain('>sessions typically 5.0 mm off<');
  });

  it('fits the shared scale to every session, not only the averages', () => {
    const byView = sessions(2);
    const side = [-30, 30];
    byView['precision-standing'] = byView['precision-standing'].map((p) => ({ ...p, xMm: side[Number(p.sessionId.slice(1))]!, yMm: 0 }));
    // The average is 0, but the sessions sit 30 mm out: the scale is the widest, 25 mm, not 5.
    expect(coachAverages(coachTrends(byView)).mpiScaleMm).toBe(25);
  });

  it('gives no typical distance for a single session', () => {
    const { svg } = renderTrendsSheet(input(1));
    expect(svg).not.toContain('sessions typically');
    expect(svg.match(/class="mpi-session"/g)).toHaveLength(4);
  });
});

describe('an MPI past the ±25 mm scale (REV-134)', () => {
  it('is pinned just inside the rim, in its own direction, and flagged', () => {
    expect(placeMpi(10, 0, 25, 0)).toEqual({ dx: 30, dy: -0, offScale: false });
    // 34.4 mm low on ±25: pinned straight down, 24 px in from the 75 px rim.
    const low = placeMpi(0, -34.4, 25, 24);
    expect(low.offScale).toBe(true);
    expect(low.dx).toBeCloseTo(0, 9);
    expect(low.dy).toBeCloseTo(51, 9);
    // Diagonal: the direction is kept.
    const diag = placeMpi(30, 30, 25, 4);
    expect(diag.dx).toBeCloseTo(71 / Math.SQRT2, 9);
    expect(diag.dy).toBeCloseTo(-71 / Math.SQRT2, 9);
  });

  it('draws an outward arrowhead for the mark, and keeps the exact offset in words', () => {
    const byView = sessions(3);
    byView['precision-standing'] = byView['precision-standing'].map((p) => ({ ...p, xMm: 0, yMm: -34.4 }));
    const { svg } = renderTrendsSheet({ ...input(3), trends: coachTrends(byView) });
    const start = svg.indexOf('data-view="precision-standing" data-metric="mpi"');
    const box = svg.slice(start);
    expect(box).toContain('class="mpi-off-scale"');
    expect(box).toContain('rotate(90)'); // straight down in the drawing
    expect(box).toContain('>avg centred · 34.4 mm low<');
    expect(box).toContain('+25 mm');
    // Views inside the scale have no arrowhead.
    const prone = svg.slice(svg.indexOf('data-view="precision-prone" data-metric="mpi"'), start);
    expect(prone).not.toContain('mpi-off-scale');
  });
});

describe('trend arrows (REV-132)', () => {
  it('need three sessions, like the trend lines', () => {
    expect(trendOf('group', [0.5, 0.4])).toBeNull();
    expect(trendOf('group', [0.5, null, 0.4])).toBeNull();
    expect(trendOf('group', [0.6, 0.5, 0.4])).toEqual({ direction: 'down', improving: true });
  });

  it('call a score rising an improvement, and a group, accuracy or MPI distance rising a worsening', () => {
    expect(trendOf('score', [80, 85, 90])).toEqual({ direction: 'up', improving: true });
    expect(trendOf('score', [90, 85, 80])).toEqual({ direction: 'down', improving: false });
    expect(trendOf('rms', [5, 7, 9])).toEqual({ direction: 'up', improving: false });
    expect(trendOf('mpi', [9, 6, 3])).toEqual({ direction: 'down', improving: true });
  });

  it('are flat when the fitted change across the range is under 5% of the average, or under the unit floor', () => {
    // 90 → 94 over the range: a change of 4 is under 5% of 92 (4.6), so steady.
    expect(trendOf('score', [90, 92, 94])).toEqual({ direction: 'flat', improving: null });
    expect(trendOf('score', [90, 93, 96])).toEqual({ direction: 'up', improving: true });
    // A small group: 0.20 → 0.21 MOA is 5% of 0.205 but under the 0.02 MOA floor.
    expect(trendOf('group', [0.2, 0.205, 0.21])).toEqual({ direction: 'flat', improving: null });
    // The MPI's distance near the centre: 0.2 → 0.6 mm is under the 0.5 mm floor.
    expect(trendOf('mpi', [0.2, 0.4, 0.6])).toEqual({ direction: 'flat', improving: null });
  });

  it('use the MPI\'s distance from the centre, whichever way it drifts', () => {
    const byView = sessions(3);
    // Prone drifts out to the left, one session at a time: (−2, 0), (−4, 0), (−6, 0).
    byView['precision-prone'] = byView['precision-prone'].map((p) => ({ ...p, xMm: -2 * (Number(p.sessionId.slice(1)) + 1), yMm: 0 }));
    const prone = coachAverages(coachTrends(byView)).views.find((v) => v.view === 'precision-prone')!;
    expect(prone.trends.mpi).toEqual({ direction: 'up', improving: false });
  });

  it('are drawn on every box from three sessions, tilted and coloured by the trend, and not at all below', () => {
    const byView = sessions(3);
    byView['precision-standing'] = byView['precision-standing'].map((p) => ({ ...p, ring: 7 + Number(p.sessionId.slice(1)) }));
    const { svg } = renderTrendsSheet({ ...input(3), trends: coachTrends(byView) });
    expect(svg.match(/class="trend-arrow"/g)).toHaveLength(4 * 4);
    const start = svg.indexOf('data-view="precision-standing" data-metric="score"');
    const box = svg.slice(start, svg.indexOf('data-metric="group"', start));
    expect(box).toContain('data-trend="up" data-improving="true"');
    expect(box).toContain('rotate(-30)');
    expect(box).toContain(TREND_COLOUR.improving);
    expect(renderTrendsSheet(input(2)).svg).not.toContain('class="trend-arrow"');
  });
});

describe('dates', () => {
  it('writes dates without the locale', () => {
    expect(shortDate('2026-09-21')).toBe('Sep 21');
    expect(shortDate('2026-01-05')).toBe('Jan 5');
  });
});
