import { Button } from '@/components/ui/button';
import { Season } from '@/lib/domain/enums';
import { SEASON_FILTERS, SEASON_FILTER_LABEL, type SeasonFilter as SeasonFilterValue } from '@/lib/domain/season';
import { renderSeasonGlyph } from '@/lib/render/condition-icons';
import { cn } from '@/lib/utils';

interface SeasonFilterProps {
  season: SeasonFilterValue;
  onSeason(season: SeasonFilterValue): void;
  /** The test ids are `<prefix>-season-<id>`. */
  testIdPrefix: string;
}

function glyph(season: Season) {
  return (
    <svg
      key={season}
      viewBox="0 0 44 44"
      className="size-6 shrink-0"
      aria-hidden="true"
      // Generated by our own pure renderer from constants only.
      dangerouslySetInnerHTML={{ __html: renderSeasonGlyph(season, 'currentColor') }}
    />
  );
}

/**
 * REV-154 (issue #29): one row of five small buttons — All (all four season pictograms in a line, same size as the
 * others, owner, 2026-10-04 — wide enough that the four season buttons share the width left over), then each season
 * as the summary image's own pictogram — that narrows a screen to the targets shot in that season. The same row on
 * Patterns, Analysis, Goals and Home.
 */
export function SeasonFilter({ season, onSeason, testIdPrefix }: SeasonFilterProps) {
  return (
    <div role="group" aria-label="Season" className="flex gap-2">
      {SEASON_FILTERS.map((id) => (
        <Button
          key={id}
          variant={id === season ? 'default' : 'outline'}
          className={cn('h-11 text-xs', id === 'all' ? 'flex shrink-0 items-center gap-1 px-2' : 'min-w-11 flex-1 px-1')}
          aria-pressed={id === season}
          aria-label={SEASON_FILTER_LABEL[id]}
          title={SEASON_FILTER_LABEL[id]}
          data-testid={`${testIdPrefix}-season-${id}`}
          onClick={() => onSeason(id)}
        >
          {id === 'all' ? Season.options.map(glyph) : glyph(id)}
        </Button>
      ))}
    </div>
  );
}
