import { Button } from '@/components/ui/button';
import { SEASON_FILTERS, SEASON_FILTER_LABEL, type SeasonFilter as SeasonFilterValue } from '@/lib/domain/season';
import { renderSeasonGlyph } from '@/lib/render/condition-icons';

interface SeasonFilterProps {
  season: SeasonFilterValue;
  onSeason(season: SeasonFilterValue): void;
  /** The test ids are `<prefix>-season-<id>`. */
  testIdPrefix: string;
}

/**
 * REV-154 (issue #29): one row of five small buttons — All, then the four seasons as the summary image's season pictograms — that
 * narrows a screen to the targets shot in that season. The same row on Patterns, Analysis, Goals and Home.
 */
export function SeasonFilter({ season, onSeason, testIdPrefix }: SeasonFilterProps) {
  return (
    <div role="group" aria-label="Season" className="grid grid-cols-5 gap-2">
      {SEASON_FILTERS.map((id) => (
        <Button
          key={id}
          variant={id === season ? 'default' : 'outline'}
          className="h-11 px-1 text-xs"
          aria-pressed={id === season}
          aria-label={SEASON_FILTER_LABEL[id]}
          title={SEASON_FILTER_LABEL[id]}
          data-testid={`${testIdPrefix}-season-${id}`}
          onClick={() => onSeason(id)}
        >
          {id === 'all' ? (
            'All'
          ) : (
            <svg
              viewBox="0 0 44 44"
              className="size-6 shrink-0"
              aria-hidden="true"
              // Generated by our own pure renderer from constants only.
              dangerouslySetInnerHTML={{ __html: renderSeasonGlyph(id, 'currentColor') }}
            />
          )}
        </Button>
      ))}
    </div>
  );
}
